export const siteConfig={
    title: 'Junior Jobs',
    description: 'Opprtunity for students and fresh-graduates to find jobs in MEAN and Egypt',
    keywords:[
        'jobs',
        'internships',
        'intern',
        'entrylevel',
        'open-source',
        'opensource',
        'open source',
        'work',
        'work from home',
        'work from home jobs',
        'work from home jobs for students',
        'work from home jobs for students in egypt',
        'work from home jobs for students in cairo',
        'jobs in egypt',
        'jobs in cairo',
        'jobs in alexandria',
        'jobs in giza',
        'intnernships in egypt',
        'intnernships in cairo',
        'intnernships in alexandria',
        'intern in egypt',
        'intern in cairo',
        'software engineer',
        'software engineer jobs',
        'software engineer jobs in egypt',
        'software engineer jobs in cairo',
        'software engineer jobs in alexandria',
        'software engineering internships',
        'software engineering internships in egypt',
        'software engineering internships in cairo',
        'software engineering internships in alexandria',
        'Software Engineering',
        'Software Engineering jobs',
        'Software Engineering jobs in egypt',
        'Software Engineering jobs in cairo',
        'internships for students',
        'internships for students in egypt',
        'internships for software engineer',
        'internships for software engineer in egypt',
        'internships for software engineer in cairo',
        'backend developer',
        'backend developer jobs',
        'backend developer jobs in egypt',
        'backend developer jobs in cairo',
        'backend developer jobs in alexandria',
        'backend developer internships',
        'backend developer internships in egypt',
        'backend developer internships in cairo',
        'backend developer internships in alexandria',
        'frontend developer',
        'frontend developer jobs',
        'frontend developer jobs in egypt',
        'frontend developer jobs in cairo',
        'frontend developer jobs in alexandria',
        'frontend developer internships',
        'frontend developer internships in egypt',
        'frontend developer internships in cairo',
        'frontend developer internships in alexandria',
        'fullstack developer',
        'fullstack developer jobs',
        'fullstack developer jobs in egypt',
        'fullstack developer jobs in cairo',
        'fullstack developer jobs in alexandria',
        'fullstack developer internships',
        'fullstack developer internships in egypt',
        'fullstack developer internships in cairo',
        'fullstack developer internships in alexandria',
        'web developer',
        'web developer jobs',
        'web developer jobs in egypt',
        'web developer jobs in cairo',
        'web developer jobs in alexandria',
        'web developer internships',
        'web developer internships in egypt',
        'web developer internships in cairo',
        'web developer internships in alexandria',
        'web development',
        'web development jobs',
        'web development jobs in egypt',
        'web development jobs in cairo',
        'web development jobs in alexandria',
        'web development internships',
        'web development internships in egypt',
        'web development internships in cairo',
        'web development internships in alexandria',
        'web designer',
        'web designer jobs',
        'web designer jobs in egypt',
        'web designer jobs in cairo',
        'Android developer',
        'Android developer jobs',
        'Android developer jobs in egypt',
        'Android developer jobs in cairo',
        'Android developer jobs in alexandria',
        'Android developer internships',
        'Android developer internships in egypt',
        'Android developer internships in cairo',
        'Android developer internships in alexandria',
        'Android development',
        'Android development jobs',
        'Android development jobs in egypt',
        'Android development jobs in cairo',
        'Android development jobs in alexandria',
        'Data analysis internships',
        'Data analysis internships in egypt',
        'Data analysis internships in cairo',
        'Data analysis internships in alexandria',
        'Data analysis',
        'Data analysis jobs',
        'Data analysis jobs in egypt',
        'Data analysis jobs in cairo',
        'Data analysis jobs in alexandria',
        'DevOps internships',
        'DevOps internships in egypt',
        'DevOps internships in cairo',
        'DevOps internships in alexandria',
        'DevOps',
        'DevOps jobs',
        'DevOps jobs in egypt',
        'DevOps jobs in cairo',
        'DevOps jobs in alexandria',
        'DevOps engineer',
        'DevOps engineer jobs',
        'DevOps engineer jobs in egypt',
    ],
}