export interface ISkill {
  skill : string
}
const skills : ISkill[] = [
{skill : `.NET`},
{skill : `.NET Framework`},
{skill : `.NET Remoting`},
{skill : `.Net Core`},
{skill : `A/B Testing`},
{skill : `API Development`},
{skill : `API Testing`},
{skill : `ASP Baton`},
{skill : `ASP.NET`},
{skill : `ASP.NET AJAX`},
{skill : `ASP.NET Core`},
{skill : `ASP.NET Core MVC`},
{skill : `ASP.NET MVC`},
{skill : `ASP.NET Web API`},
{skill : `AWS`},
{skill : `Adobe`},
{skill : `Adobe Analytics`},
{skill : `Adobe Animate`},
{skill : `Adobe Audition`},
{skill : `Adobe Bridge`},
{skill : `Adobe Camera Raw`},
{skill : `Adobe Illustrator`},
{skill : `Adobe Photoshop`},
{skill : `Adobe Portfolio`},
{skill : `Agile`},
{skill : `Algorithm Analysis`},
{skill : `Algorithm Design`},
{skill : `Algorithm Development`},
{skill : `Algorithm Optimization`},
{skill : `Algorithms`},
{skill : `Alpine`},
{skill : `Amazon CloudFront`},
{skill : `Amazon Dynamodb`},
{skill : `Amazon EBS`},
{skill : `Amazon EC2`},
{skill : `Amazon Kindle`},
{skill : `Amazon Marketplace`},
{skill : `Amazon Mechanical Turk`},
{skill : `Amazon RDS`},
{skill : `Amazon Redshift`},
{skill : `Amazon S3`},
{skill : `Amazon SQS`},
{skill : `Amazon SimpleDB (SDB)`},
{skill : `Amazon VPC`},
{skill : `Amazon Web Services`},
{skill : `Amazon Web Services (AWS)`},
{skill : `Android`},
{skill : `Android Development`},
{skill : `Android Games`},
{skill : `Android SDK`},
{skill : `Android Studio`},
{skill : `Android Support`},
{skill : `Android Testing`},
{skill : `Angular`},
{skill : `AngularFire`},
{skill : `AngularJS`},
{skill : `Apache`},
{skill : `Apache Ant`},
{skill : `Apache CXF`},
{skill : `Apache Camel`},
{skill : `Apache Commons`},
{skill : `Apache Cordova`},
{skill : `Apache Derby`},
{skill : `Apache FOP`},
{skill : `Apache Foundation`},
{skill : `Apache HTTP Server`},
{skill : `Apache Ivy`},
{skill : `Apache Kafka`},
{skill : `Apache Mesos`},
{skill : `Apache MyFaces Tomahawk`},
{skill : `Apache Pig`},
{skill : `Apache Spark`},
{skill : `Apache Storm`},
{skill : `Apache Tiles`},
{skill : `Apache Velocity`},
{skill : `Apache ZooKeeper`},
{skill : `App`},
{skill : `App Builder`},
{skill : `App Inventor`},
{skill : `App Store`},
{skill : `Apple`},
{skill : `Apple Aperture`},
{skill : `Apple Certified`},
{skill : `Apple Color`},
{skill : `Apple Compressor`},
{skill : `Apple Developer`},
{skill : `Apple Hardware`},
{skill : `Apple Motion`},
{skill : `Apple Music`},
{skill : `Apple Numbers`},
{skill : `Apple Pages`},
{skill : `Astrojs`},
{skill : `Bash`},
{skill : `Bootstrap`},
{skill : `C Programming`},
{skill : `C Suite`},
{skill : `C#`},
{skill : `C++`},
{skill : `C++ Builder`},
{skill : `C++/CLI`},
{skill : `Ionic`},
{skill : `Ionic Framework`},
{skill : `Jasmine`},
{skill : `Jasmine Framework`},
{skill : `Jasper`},
{skill : `Jasper Reports`},
{skill : `Java`},
{skill : `Java API`},
{skill : `Java AWT`},
{skill : `Java Applets`},
{skill : `Java Architecture for XML Binding (JAXB)`},
{skill : `Java Certified Programmer`},
{skill : `Java Concurrency`},
{skill : `Java Database Connectivity (JDBC)`},
{skill : `Java Enterprise Architecture`},
{skill : `Java Enterprise Edition`},
{skill : `Java Frameworks`},
{skill : `Java Message Service (JMS)`},
{skill : `Java Naming and Directory Interface (JNDI)`},
{skill : `Java Native Interface (JNI)`},
{skill : `Java Performance`},
{skill : `Java RMI`},
{skill : `Java Security`},
{skill : `Java Swing`},
{skill : `Java Virtual Machine (JVM)`},
{skill : `Java Web Server`},
{skill : `Java Web Services`},
{skill : `Java Web Start`},
{skill : `Java2D`},
{skill : `Java3D`},
{skill : `JavaBeans`},
{skill : `JavaCC`},
{skill : `JavaCard`},
{skill : `JavaFX`},
{skill : `JavaMail`},
{skill : `JavaSE`},
{skill : `JavaScript Frameworks`},
{skill : `JavaScript Libraries`},
{skill : `JavaScriptMVC`},
{skill : `JavaServer Faces (JSF)`},
{skill : `JavaServer Pages (JSP)`},
{skill : `JavaServer Pages Standard Tag Library (JSTL)`},
{skill : `Javadoc`},
{skill : `Javascript`},
{skill : `Jave`},
{skill : `PHP`},
{skill : `PHP Applications`},
{skill : `PHP Frameworks`},
{skill : `PHPList`},
{skill : `PHPNuke`},
{skill : `PHPUnit`},
{skill : `Spring`},
{skill : `Spring 14`},
{skill : `Spring Batch`},
{skill : `Spring Boot`},
{skill : `Spring Cleaning`},
{skill : `Spring Cloud`},
{skill : `Spring DI`},
{skill : `Spring DM`},
{skill : `Spring Data`},
{skill : `Spring Data JPA`},
{skill : `Spring Design`},
{skill : `Spring Framework`},
{skill : `Spring Integration`},
{skill : `Spring MVC`},
{skill : `Spring Roo`},
{skill : `Spring Security`},
{skill : `Spring Webflow`},
{skill : `SpringSource`},
<<<<<<< HEAD
=======

>>>>>>> 23b526fce5af6fcde0ba2b143eb75ab802e08dc4
{skill : `Test Assurance`},
{skill : `Test Automation`},
{skill : `Test Automation Framework`},
{skill : `Test Automation Tools`},
{skill : `Test Case Generation`},
{skill : `Test Cases`},
{skill : `Test Coordination`},
{skill : `Test Coverage`},
{skill : `Test Data`},
{skill : `Test Design`},
{skill : `Test Designing`},
{skill : `Test Development`},
{skill : `Test Driven Development`},
{skill : `Web`},
{skill : `Web & Mobile`},
{skill : `Web + Interactive`},
{skill : `Web 2.0`},
{skill : `Web 2.0 Development`},
{skill : `Web API`},
{skill : `Web Acceleration`},
{skill : `Web Access`},
{skill : `Web Analytics`},
{skill : `Web Application Design`},
{skill : `Web Application Development`},
{skill : `Web Application Firewall`},
{skill : `Web Application Security`},
{skill : `Web Application Security Assessment`},
{skill : `Web Applications`},
{skill : `Web Apps`},
{skill : `Web Architecture`},
{skill : `Web Authoring`},
{skill : `Web Authoring Tools`},
{skill : `Web Based Media`},
{skill : `Web Broadcasting`},
{skill : `Web Browsing`},
{skill : `Web Caching`},
{skill : `Web Campaigns`},
{skill : `Web Chat`},
{skill : `Web Collaboration`},
{skill : `Web Commercials`},
{skill : `Web Community Management`},
{skill : `Web Concepts`},
{skill : `Web Conferencing`},
{skill : `Web Consultancy`},
{skill : `Web Content Accessibility Guidelines (WCAG)`},
{skill : `Web Content Creation`},
{skill : `Web Content Optimization`},
{skill : `Web Content Production`},
{skill : `Web Content Writing`},
{skill : `Web Crawling`},
{skill : `Web Design`},
{skill : `Web Design Business`},
{skill : `Web Development`},
{skill : `Web Editing`},
{skill : `Web Engineering`},
{skill : `Web Experience`},
{skill : `Web Fonts`},
{skill : `Web Foundations`},
{skill : `Web Framework`},
{skill : `Web Games`},
{skill : `Web Governance`},
{skill : `Web Graphics`},
{skill : `Web Handling`},
{skill : `Web Help`},
{skill : `Web Hosting`},
{skill : `Web Intelligence`},
{skill : `Web Interface Design`},
{skill : `Web Languages`},
{skill : `Web Maintenance`},
{skill : `Web Mapping`},
{skill : `Web Marketing Strategy`},
{skill : `Web Media`},
{skill : `Web Metrics`},
{skill : `Web Mining`},
{skill : `Web Navigation`},
{skill : `Web Operations`},
{skill : `Web Pages`},
{skill : `Web Parts`},
{skill : `Web Performance`},
{skill : `Web Presence`},
{skill : `Web Presentations`},
{skill : `Web Production Management`},
{skill : `Web Products`},
{skill : `Web Project Management`},
{skill : `Web Projects`},
{skill : `Web Report Studio`},
{skill : `Web Sales`},
{skill : `Web Savvy`},
{skill : `Web Scraping`},
{skill : `Web Series`},
{skill : `Web Servers`},
{skill : `Web Service Development`},
{skill : `Web Services`},
{skill : `Web Services API`},
{skill : `Web Services Description Language (WSDL)`},
{skill : `Web Services Management`},
{skill : `Web Site Editing`},
{skill : `Web Site Production`},
{skill : `Web Solutions`},
{skill : `Web Standards`},
{skill : `Web Strategy`},
{skill : `Web TV`},
{skill : `Web Technologies`},
{skill : `Web Testing`},
{skill : `Web Text`},
{skill : `Web Tracking`},
{skill : `Web Traffic`},
{skill : `Web Typography`},
{skill : `Web Video`},
{skill : `Web mobile`},
{skill : `Web móvil`},
{skill : `Web of Science`},
{skill : `Web-Konferenzen`},
{skill : `Web-Standards`},
{skill : `Web-based Communication`},
{skill : `Web-based Project Management`},
{skill : `Web-based Reporting`},
{skill : `Web-based Research`},
{skill : `Web-based Software Development`},
{skill : `Web-based Solutions`},
{skill : `Web-based Surveys`},
{skill : `Web-based Systems`},
{skill : `Web-to-print`},
{skill : `Web2py`},
{skill : `WebADI`},
{skill : `WebCEO`},
{skill : `WebCT`},
{skill : `WebCenter`},
{skill : `WebDAV`},
{skill : `WebDev`},
{skill : `WebDriver`},
{skill : `WebDynpro`},
{skill : `WebEOC`},
{skill : `WebEx`},
{skill : `WebFOCUS`},
{skill : `WebGL`},
{skill : `WebGUI`},
{skill : `WebInspect`},
{skill : `WebKit`},
{skill : `WebLogic`},
{skill : `WebMatrix`},
{skill : `WebOS`},
{skill : `WebObjects`},
{skill : `WebPDM`},
{skill : `WebScarab`},
{skill : `WebSockets`},
{skill : `WebSphere`},
{skill : `WebSphere Adapters`},
{skill : `WebSphere Application Server`},
{skill : `WebSphere Business Integration`},
{skill : `WebSphere ESB`},
{skill : `WebSphere Integration Developer`},
{skill : `WebSphere MQ`},
{skill : `WebSphere Message Broker`},
{skill : `WebSphere Portal`},
{skill : `WebSphere Portlet Factory`},
{skill : `WebSphere Process Server`},
{skill : `WebTAS`},
{skill : `WebTrends Analytics`},
{skill : `WebUI`},
{skill : `WebWorks`},
{skill : `Webcam`},
{skill : `Webcasting`},
{skill : `Webdesign`},
{skill : `Webdesign-Business`},
{skill : `Webflow`},
{skill : `Webgrafik`},
{skill : `Webi`},
{skill : `Webinar Development`},
{skill : `Webinar Management`},
{skill : `Webisodes`},
{skill : `Weblogic Administration`},
{skill : `Weblogs`},
{skill : `Webmail`},
{skill : `Webmaster Services`},
{skill : `Webmaster Tools`},
{skill : `Webmin`},
{skill : `Webpack`},
{skill : `Webquests`},
{skill : `Webroot`},
{skill : `Webrtc`},
{skill : `Websense`},
{skill : `Website Administration`},
{skill : `Website Authoring`},
{skill : `Website Branding`},
{skill : `Website Building`},
{skill : `Website Consultation`},
{skill : `Website Graphics`},
{skill : `Website Localization`},
{skill : `Website Merchandising`},
{skill : `Website Monetization`},
{skill : `Website Promotion`},
{skill : `Website Translation`},
{skill : `Website Updating`},
{skill : `Back-End Web Development`},
{skill : `Back-end Operations`},
{skill : `Backbase`},
{skill : `Backbone.js`},
{skill : `RESTful WebServices`},
{skill : `RESTful architecture`},
{skill : `React Native`},
{skill : `React.js`},
{skill : `ReactJS`},
{skill : `Next.js`},
{skill : `NextJS`},
{skill : `API`},
{skill : `Vue.js`},
{skill : `VueJS`},
{skill : `AngularJS`},
{skill : `Angular.js`},
{skill : `Angular`},
{skill : `CI/CD`},
{skill : `Ansible`},
{skill : `Docker`},
{skill : `HTML`},
{skill : `HTML5`},
{skill : `CSS`},
{skill : `CSS3`},
{skill : `JavaScript`},
{skill : `Node.js`},
{skill : `NodeJS`},
{skill : `PHP`},
{skill : `Python`},
{skill : `Ruby`},
{skill : `Ruby on Rails`},
{skill : `Rust`},
{skill : `Go`},
{skill : `Java`},
{skill : `C#`},
{skill : `C++`},
{skill : `C`},
{skill : `Cobol`},
{skill : `Scala`},
{skill : `Kotlin`},
{skill : `Swift`},
{skill : `Objective-C`},
{skill : `TypeScript`},
{skill : `SQL`},
{skill : `MySQL`},
{skill : `PostgreSQL`},
{skill : `MongoDB`},
{skill : `Redis`},
{skill : `GraphQL`},
{skill : `AWS`},
{skill : `Azure`},
{skill : `Google Cloud`},
{skill : `Firebase`},
{skill : `Heroku`},
{skill : `Git`},
{skill : `GitHub`},
{skill : `GitLab`},
{skill : `Bitbucket`},
{skill : `Jira`},
{skill : `Confluence`},
{skill : `Trello`},
{skill : `Slack`},
{skill : `Discord`},
{skill : `Zoom`},
{skill : `ServerLess`},
{skill : `Serverless`},
{skill : `Serverless Framework`},
{skill : `Serverless Functions`},
{skill : `microservices`},
{skill : `Microservices`},
{skill : `Microservices Architecture`},
{skill : `Microservices Design`},
{skill : `testing`},
{skill : `Testing`},
{skill : `Unit Testing`},
{skill : `Integration Testing`},
{skill : `Functional Testing`},
{skill : `End-to-End Testing`},
{skill : `Performance Testing`},
{skill : `Security Testing`},
{skill : `Regression Testing`},
{skill : `Smoke Testing`},
{skill : `Exploratory Testing`},
{skill : `Usability Testing`},
{skill : `MochaJS`},
{skill : `Mocha.js`},
{skill : `Mocha`},
{skill : `Jest`},
{skill : `Jasmine`},
{skill : `Cypress`},
{skill : `Selenium`},
{skill : `Protractor`},
{skill : `Nightwatch`},
{skill : `Chai`},
{skill : `CircleCI`},
{skill : `TravisCI`},
{skill : `Jenkins`},
{skill : `Karma`},
{skill : `JMeter`},
{skill : `LoadRunner`},
{skill : `Postman`},
{skill : `SoapUI`},
{skill : `Redux`},
{skill : `Redux.js`},
{skill : `ReduxJS`},

] 
export default skills;